# Generated by Django 5.2.7 on 2025-10-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='The unique short code for the URL', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times this URL was accessed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this short URL is active')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='shortener_u_short_c_50dfff_idx'), models.Index(fields=['-created_at'], name='shortener_u_created_d57324_idx')],
            },
        ),
    ]
